### ISSUE TITLE
XBMC Launcher not shown in Marshmallow

### ISSUE THREAD

**Issue by BuddyLuvve** [blunden/XBMCLauncher#10]
The option to use this as the default launcher is broken in Marshmallow. My install is purely for my mother to use Kodi, and as such this launcher was fantastic! It took all of the complication away from using it! I'd love to help if we can get it working again! I'm not sure what info would be of use to you, but here's my setup:

Device: Nexus Player
OS: Stock, latest update
XBMC install: Stock Kodi app from Play Store
XBMCLauncher is latest version as well.

Let me know if I can provide anything further.

Thanks,
BuddyLuvve

**Comment by blunden** [comment]
Unfortunately there is an issue with changing the default launcher in Marshmallow on Android TV devices for some reason. Other launchers have the same issue from what I've seen.

I've had multiple users report this issue but have yet to find a solution unfortunately. The only potential workaround I know of at this time is to downgrade to Lollipop.

**Comment by BuddyLuvve** [comment]
I noticed that someone figured out how to edit Kodi to act as a launcher on the Nexus Player... Maybe he has an idea on how to get it to work. I can send a message tomorrow and see what he changed.
http://forum.xda-developers.com/nexus-player/themes-apps/kodi-14-2-x86-launcher-manifest-t3125625

**Comment by blunden** [comment]
Does that one still work on Marshmallow though? XBMC Launcher worked just fine on the Nexus Player before that update.

**Comment by BuddyLuvve** [comment]
I'm not sure. I'll sideload it tonight and see if it works.

**Comment by blunden** [comment]
@BuddyLuvve Would you mind testing this and see if it solves the issue?

https://www.dropbox.com/s/xr7x9tj3yxko8os/XBMCLauncher-leanback-test.apk?dl=0

**Comment by blunden** [comment]
It seems to be pointless trying to get it working. Google simply doesn't want it to be.

https://code.google.com/p/android/issues/detail?id=191828
