### ISSUE TITLE
Video stops playing when pressing home button

### ISSUE THREAD

**Issue by ErAzOr2k** [blunden/XBMCLauncher#11]
Hi,

when I press the home button while watching a video it stops the playback.
It would be nicer if this app just returns to home screen in this case but not stopping the video.
Is this possible?

Thanks

**Comment by blunden** [comment]
Hi,

That is out of my control. This app does nothing more than launch Kodi whenever Android calls the launcher and as such it has no control of what happens inside Kodi.

Thank you for taking the time to post a suggestion though.
