### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by ErAzOr2k** [blunden/XBMCLauncher#13]
Can you pleade add support for the new SPMC?
http://spmc.semperpax.com/

Thanks

**Comment by blunden** [comment]
Hi,

As far as I am aware SPMC already supports being set as the launcher. Is that no longer true?

**Comment by blunden** [comment]
Also, I thought I already added support for SPMC in the past. Have you verified that the current SPMC entry doesn't work anymore?

**Comment by ErAzOr2k** [comment]
yes the activity has been changed to  com.semperpax.spmc16/com.semperpax.spmc16.Splash

**Comment by blunden** [comment]
I see. I'm away on vacation this week but I'll try to remember to update it when I get back.

**Comment by ErAzOr2k** [comment]
thank you :)

**Comment by blunden** [comment]
A new update was just published on the Play Store. Give it a few hours to propagate and let me know.
