### ISSUE TITLE
Playstore link not working

### ISSUE THREAD

**Issue by Dalto1** [blunden/XBMCLauncher#15]
I cannot access to the app on the playstore

https://play.google.com/store/apps/details?id=se.blunden.xbmclauncher

**Comment by blunden** [comment]
The app was suspended for policy violations but reinstated after a successful appeal. I need to make some changes to it first though so it will remain unavailable until I find the time to do so.

**Comment by Dalto1** [comment]
Thanks!

**Comment by Thrilleratplay** [comment]
@blunden In the mean time, have you considered submitting it to [Fdroid](https://gitlab.com/fdroid/rfp/issues)?

**Comment by blunden** [comment]
@Thrilleratplay No, I haven't. That would just increase the effort and support requests most likely. 

Also, I don't like that they resign apps, making them incompatible. If they use the same key to sign all apps, it likely also means that apps on FDroid can read each other's data which is of course a huge security issue. Maybe they addressed that issue somehow though.

**Comment by blunden** [comment]
A new version has been submitted for review. Let's see if it appeases the Play Store team. :)
