### ISSUE TITLE
Emby

### ISSUE THREAD

**Issue by Dalto1** [blunden/XBMCLauncher#16]
Dont know if this is possible, but i would like to have a emby launcher. Its an alternative to plex or kodi.

https://play.google.com/store/apps/details?id=tv.emby.embyatv
and
https://play.google.com/store/apps/details?id=com.mb.android

**Comment by blunden** [comment]
Does it have a way to launch other apps from inside Emby? If not, you will get stuck inside it and only be able to get out of it using ADB (if you have it enabled).

**Comment by Dalto1** [comment]
I dont think there is a way to launch apps from inside. You cannot change launcher via settings?

**Comment by blunden** [comment]
If you would set Emby as the launcher, you would be unable to reach settings or any other app unless using ADB. Emby would be your launcher, i.e your "desktop" equivalent.

**Comment by Dalto1** [comment]
I think i got an icon in the app drawer for settings on my device, but maybe not everyone got it.

**Comment by blunden** [comment]
You need a way to get to that from inside Emby since you will be unable to exit the app the normal way. The word "launcher" has a special meaning in Android terminology.

**Comment by Dalto1** [comment]
Thanks, I'll let you know when there will be a way to launch apps in emby
