### ISSUE TITLE
Publish through F-Droid

### ISSUE THREAD

**Issue by muelli** [blunden/XBMCLauncher#20]
It'd be nice to have this app published through F-Droid.

Have you looked into it and ran into issues?

**Comment by blunden** [comment]
F-Droid resigns apps with their own keys last time I checked. I don't like having multiple incompatible APKs out there.

**Comment by muelli** [comment]
If I understand https://f-droid.org/en/docs/Reproducible_Builds/ correctly, then you can use your own binaries, provided that your builds are reproducible.

**Comment by muelli** [comment]
yeah, well. The benefits of reproducible builds include more than publishing your custom binary instead of having it signed by fdroid, though. Here's a bit of propaganda: https://reproducible-builds.org/
In the end, somebody needs to actually do the work. Having an open bug about this allows volunteers to direct their workforce towards achieving this goal.
