### ISSUE TITLE
Kodi restarts every time I go home from another app on Shield TV Android 11 

### ISSUE THREAD

**Issue by nsingh94** [blunden/XBMCLauncher#21]
Hi - This app worked perfectly on Android 9 on the Shield TV.
Now that the shield is on Android 11, when I go to another app then go home, it’s a black screen and then Kodi starts again. Does the app need to be updated for Android 11 so that kodi as the launcher doesn’t close once I go to a different app?

Let me know if there is any other information I can provide. And thanks so much for the app, I’ve been using it to make kodi my launcher for several years :-)

**Comment by blunden** [comment]
I don't think that's necessarily something that has anything to do with this app. I've noticed that Kodi doesn't stay running in the background nearly as often as before since the move to Android 11 on the Shield when using the default Android TV launcher.

**Comment by nsingh94** [comment]
Hi blunden - Thanks for taking a look! So, I just played around with this and now think that this isn't about Kodi being killed in the background. I found that hitting the home button from another app results in Kodi being restarted, whereas hitting the back button from another app results in the original Kodi instance being brought back.
I tried this using the YouTube app. I launched YouTube from Kodi as the launcher, watched some videos, hit the back button and was brought back to the same instance of Kodi I opened the app from. I tried this again but this time hit the home button, and the screen goes black and then Kodi restarted (same happened even I opened YouTube for only a few seconds). Sometime after hitting the home button, the screen stays black, Kodi never relaunches, and I have to restart the Shield.

Does this change your assessment in any way?

**Comment by blunden** [comment]
Could you provide a logcat log (and possibly also a Kodi log)? Maybe the recently merged pull request makes a difference, but without the logs it's hard to say what's actually happening.

**Comment by Heptanas** [comment]
Same shit. Android tv 12

**Comment by blunden** [comment]
I've noticed how often Android TV on my Nvidia Shield TV kills Kodi if it's inactive in the background, so I'm not sure there is anything I can do about it.

**Comment by Heptanas** [comment]
So there is no trick for fix it? In old tv box with android 7 and 2gb ram works fine but not in kodi with android tv 12 and 4 gb ram. Why android tv kill kodi?

**Comment by blunden** [comment]
Not that I know of. If there is, feel free to find it and link it, or submit a pull request. 🙂

**Comment by Heptanas** [comment]
Kodi nerds maven build works fine in background and not kill. Butt not original kodi.
