### ISSUE TITLE
lose root access after reboot.

### ISSUE THREAD

**Issue by OEvgeny** [blunden/XBMCLauncher#6]
Hello you answered to my comment on google play store:

"Weird. Do you lose root access for all apps or just Kodi? The only reason I could think of in the latter case is that it somehow fails a root check because it starts up too fast. Which root manager are you using?"

Decided to answer here.
Yes, I lose root access for all apps, but then I push home button, I got it again and Kodi restarts.
It looks like after each reboot all apps that need root access reporting to me, what I have not it, but when I press home button (on my remote) Kodi restarts and I got root acces.

I'm using android 4.4.4, and SuperSu app (https://play.google.com/store/apps/details?id=eu.chainfire.supersu).
Tried to reinstall it from google play but it didn't solve my problem.

BTW Thanks for this app!

**Comment by blunden** [comment]
I find that really weird, but clearly it's happening. The su daemon should start up long before my app starts Kodi. I don't really understand what makes my app or Kodi trigger it but not basically any other launcher.

Could you run a logcat during boot and until you have regained root by pressing the Home button? Maybe that will provide some clues.

**Comment by OEvgeny** [comment]
Ok, I will try to run logcat in a few days.

**Comment by OEvgeny** [comment]
Here is the gist: https://gist.github.com/OEvgeny/af74a39cb5238706b521
Running with:

    adb.exe -d logcat > log.txt

while devise was booting.

This time I press home button 3 or 4 times because Kodi won't restart.
First Kodi launch is on line

    3229  V/Kodi    (  745): virtual void CXBMCApp::onStart(): 

Next when I press Home button 1st time

    4075  V/Kodi    (  745): virtual void CXBMCApp::onStart(): 
    4077  V/Kodi    (  745): virtual void CXBMCApp::onStart(): Already running, ignoring request to start

And next times

    4363  V/Kodi    (  745): virtual void CXBMCApp::onStart(): 
    4365  V/Kodi    (  745): virtual void CXBMCApp::onStart(): Already running, ignoring request to start
    ...
    4875  V/Kodi    (  745): virtual void CXBMCApp::onStart(): 
    4877  V/Kodi    (  745): virtual void CXBMCApp::onStart(): Already running, ignoring request to start
    ...
    4989  V/Kodi    (  745): virtual void CXBMCApp::onStart(): 
    4991  V/Kodi    (  745): virtual void CXBMCApp::onStart(): Already running, ignoring request to start

And than a last time:

    5881  V/Kodi    ( 2027): virtual void CXBMCApp::onStart():

**Comment by blunden** [comment]
Thanks! I'll take a look at this and see if something stands out.

**Comment by blunden** [comment]
@OEvgeny Can you confirm the line below happens after you have pressed the HOME button, ie. not until you do what you have to to get root? If so, it seems like there might be a general problem with android.intent.action.BOOT_COMPLETED not getting delivered.

I/ActivityManager(  495): Start proc eu.chainfire.supersu for broadcast eu.chainfire.supersu/.BootCompleteReceiver: pid=1382 uid=10001 gids={50001}

**Comment by OEvgeny** [comment]
Sorry, miss your comment.
After some testing I know that I just need to restart kodi to get root after each reboot. But when I press home button first times (before kodi restarts) it restarts kodi, and I get root.

**Comment by OEvgeny** [comment]
I can provide log with simple restart kodi after reboot by closing it if needed.

**Comment by OEvgeny** [comment]
And yes, I can comfirm that all I need to get root after reboot is restart kodi. No need to do rooting procedure. Also I have rom with root out of the box.

**Comment by blunden** [comment]
@OEvgeny I would appreciate if you could try version 2.4 that was just uploaded to the Play Store. I realize that you might have moved on to a different app.

**Comment by OEvgeny** [comment]
@blunden I will try asap :) And let you know. Thanks!

**Comment by blunden** [comment]
With this change I see the BOOT_COMPLETED broadcast being sent at least. Do note that it might take 10-30 seconds for it to happen.
