### ISSUE TITLE
Kodi 15.0 – Isengard support?

### ISSUE THREAD

**Issue by kingdingaling83** [blunden/XBMCLauncher#9]
for some reason it wont launch the new kodi from the play store.

**Comment by blunden** [comment]
Sounds like they changed the package name. I'm on vacation and will be so until the middle of august. I'll try to get to when I get home.

**Comment by kingdingaling83** [comment]
my mistake,
an uninstall and reinstall fixed it!
sorry!
chris

**Comment by blunden** [comment]
Great!
